### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by hghuoiuopuut** [HekaHub/Discord-Voice-Manager#2]
файла dist нету не работает, автоматически папка не появляется эта хз почему не работает.

**Comment by HekaHub** [comment]
> файла dist нету не работает, автоматически папка не появляется эта хз почему не работает.

Компилируй

**Comment by hghuoiuopuut** [comment]
не знаю у меня ошибка не запускается.

**Comment by hghuoiuopuut** [comment]
![image](https://user-images.githubusercontent.com/109924113/182960517-10521863-2e6d-45df-8898-da83545df164.png)

**Comment by hghuoiuopuut** [comment]
![image](https://user-images.githubusercontent.com/109924113/182967193-4902705c-5059-45bd-bf4a-26d35cbbc547.png)

**Comment by arlenrww** [comment]
ты дурачок потому что

**Comment by hghuoiuopuut** [comment]
согласен

> ты дурачок потому что

**Comment by HekaHub** [comment]
> согласен
> 
> > ты дурачок потому что
> 
> 

Поэтому думай головой
