### ISSUE TITLE
Не могу настроить базу данных

### ISSUE THREAD

**Issue by SenexT1** [HekaHub/Discord-Voice-Manager#3]
Помогите, постоянно бот не может подключиться к базе данных какие форумы я бы не читал.
node:events:491
      throw er; // Unhandled 'error' event
      ^

MongooseError: Operation `room.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\mrmik\Desktop\Discord-Voice-Manager-main\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:153:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Emitted 'error' event on Core instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)

**Comment by HekaHub** [comment]
мужик, мб кривая ссылка на монго, но это точно не ко мне

**Comment by arlenrww** [comment]
> 

да брат

**Comment by HekaHub** [comment]
В конфиге ссылку нормальную поставь на монго. Там в комментарии сайт где её генерировать укзаан :(

**Comment by SenexT1** [comment]
![image](https://user-images.githubusercontent.com/100101032/189121470-11ff92ba-3998-4cc6-a711-81ce7a22efc3.png)

это?

**Comment by HekaHub** [comment]
Да, там вместо <password> пишешь пароль от бд

**Comment by SenexT1** [comment]
> Да, там вместо пишешь пароль от бд

Пробую, сейчас гляну что получится

**Comment by SenexT1** [comment]
Ему абсолютно поебать.

**Comment by SenexT1** [comment]
`node:events:491
      throw er; // Unhandled 'error' event
      ^

MongooseError: Operation `room.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\mrmik\Desktop\Discord-Voice-Manager-main\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:153:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Emitted 'error' event on Core instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)`

**Comment by HekaHub** [comment]
В консоли есть сообщение "База данных подключена."?

**Comment by SenexT1** [comment]
Нет

**Comment by HekaHub** [comment]
Значит проблема точно с коннектом базы данных. Я не знаю с чем именно это может связано, если вы правильно вставляете ссылку. Может быть поможет:
https://stackoverflow.com/questions/65408618/mongooseerror-operation-users-findone-buffering-timed-out-after-10000ms
https://github.com/Automattic/mongoose/issues/9732?ysclid=l7t1c6tuxv226877839
https://programbox.ru/2022/01/13/%D0%BA%D0%B0%D0%BA-%D1%83%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%82%D1%8C-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D1%83-%D0%B2%D1%80%D0%B5%D0%BC%D1%8F-%D0%BE%D0%B6%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B1/?ysclid=l7t1cerdqv919180184

**Comment by SenexT1** [comment]
Так, отлично, еблан все таки я
Бот заработал, но появилась другая проблема, теперь он выкидывает из комнаты создания приватных комнат

**Comment by SenexT1** [comment]
Все, спасибо большое за приватные комнаты. Я просто не правильно ссылку на бд вставлял. Там где <password> я писал пароль вместе с этими <>, а нужно было без них. После все заработало.
