### ISSUE TITLE
Не могу запустить скрипт

### ISSUE THREAD

**Issue by Graff1ks** [HekaHub/Discord-Voice-Manager#4]
Помогите, пожалуйста. Когда запускаю скрипт, config.ts выдает такую ошибку:

[Running] ts-node "d:\Пользователи\Graffiks\Загрузки\skeletBotByStrelok-main\src\config.ts"

[Done] exited with code=0 in 2.217 seconds

Пытался найти решение на форумах, на ютубе и тд. Ничего не помогает. Заранее большое спасибо!

**Comment by HekaHub** [comment]
https://stackoverflow.com/questions/62461708/exited-with-code-0-in-0-074-seconds-output-window-has-no-output-in-visual-stud

**Comment by HekaHub** [comment]
А вообще компилируй код
npx tsc либо tsc --build и потом когда появится dist запускаешь файл из dist основной

**Comment by Graff1ks** [comment]
А что тут делать?
![image](https://user-images.githubusercontent.com/111047553/190839180-5ee9aa61-1320-4d9b-aecf-3f6401ba5b28.png)

**Comment by Graff1ks** [comment]
Извиняюсь за свою глупость, просто не очень разбираюсь.

**Comment by HekaHub** [comment]
Загрузить по нормальному все файлы с репозиторя включая tsconfig

**Comment by Graff1ks** [comment]
Как скомпилировать файл и скачать по нормальному файлы с репозитория включая tsconfig?

**Comment by kuwialcs** [comment]
C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22
        res.channelId = member.voice.channel.id;
                      ^

TypeError: Cannot set properties of null (setting 'channelId')
    at MessageCollector.<anonymous> (C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by HekaHub** [comment]
> C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22
>         res.channelId = member.voice.channel.id;
>                       ^
> 
> TypeError: Cannot set properties of null (setting 'channelId')
>     at MessageCollector.<anonymous> (C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22:23)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> 

Загрузи репу по новой

**Comment by kuwialcs** [comment]
> > C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22
> > res.channelId = member.voice.channel.id;
> > ^
> > TypeError: Cannot set properties of null (setting 'channelId')
> > at MessageCollector. (C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22:23)
> > at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> Загрузи репу по новой

Права от овнера ушли, но к тому кому передали они не пришли.

**Comment by Graff1ks** [comment]
всем привет, помогите пожалуйста. вылезла другая ошибка, которая появилась просто так:
![image](https://user-images.githubusercontent.com/111047553/190913436-8834241c-94c8-473a-a918-4b59a39e6096.png)
не понимаю в чем проблема, пытался решить, но ничего не получается. заранее большое спасибо!

**Comment by HekaHub** [comment]
> 
> > > C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22
> > > res.channelId = member.voice.channel.id;
> > > ^
> > > TypeError: Cannot set properties of null (setting 'channelId')
> > > at MessageCollector. (C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22:23)
> > > at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > 
> > Загрузи репу по новой
> 
> Права от овнера ушли, но к тому кому передали они не пришли.

Коммитнул решение

**Comment by kuwialcs** [comment]
> > 
> > > > C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22
> > > > res.channelId = member.voice.channel.id;
> > > > ^
> > > > TypeError: Cannot set properties of null (setting 'channelId')
> > > > at MessageCollector. (C:\Users\kuwialcs\3D Objects\Discord-Voice\dist\buttons\Owner.js:22:23)
> > > > at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > > 
> > > Загрузи репу по новой
> > 
> > Права от овнера ушли, но к тому кому передали они не пришли.
> 
> Коммитнул решение

А нельзя сделать чтоб owner в config мог изменять настройки любых рум?

**Comment by HekaHub** [comment]
в конфиг нет, только если ручками в бд самому

**Comment by Graff1ks** [comment]
всем привет, помогите кто-то, пожалуйста. не может присоединится к базе данных mongodb. пишу без <> правильный пароль, но ничего не работает. 

сама ошибка:
node:events:491
      throw er; // Unhandled 'error' event
      ^

MongooseError: Operation `room.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (d:\Пользователи\Graffiks\Загрузки\Discord-Voice-Manager-main\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:151:23)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Emitted 'error' event on Core instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
    
    заранее спасибо, кто поможет!!

**Comment by kuwialcs** [comment]
> в конфиг нет, только если ручками в бд самому

Хека, а мут и размут без disconnect некак ибо база должна обновить?

**Comment by HekaHub** [comment]
> kuwialcs

не бд, а дискорд. Можно ещё перемещать по каналам
